### ISSUE TITLE
Suggestion: Disable client access to mod server config 

### ISSUE THREAD

**Issue by TheBambino** [JavidPack/HEROsMod#68] opened 2021-06-02 14:02 UTC
Ability to blanketly disable clients aside from admin to have access to changing server-side config. This was an issue that was brought up in the TML repo but it's been about a year. Considering the nature of HEROsMod, I figured this ability may fit better here.

**Comment by JavidPack** [comment] 2021-06-04 15:28
Thanks for the suggestions, I'm aware of this idea. Closing as this is a Duplicate of #46

**Closed by JavidPack** 2021-06-04 15:28 UTC
